name: TimeTrackerVoice
options:
  bundleIdPrefix: com.timetracker
  deploymentTarget:
    iOS: "17.0"
  xcodeVersion: "15.0"
  generateEmptyDirectories: true

settings:
  base:
    DEVELOPMENT_TEAM: ""
    SWIFT_VERSION: "5.9"
    ENABLE_USER_SCRIPT_SANDBOXING: NO

targets:
  TimeTrackerVoice:
    type: application
    platform: iOS
    sources:
      - TimeTrackerVoice
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.timetracker.voice
        INFOPLIST_FILE: TimeTrackerVoice/Resources/Info.plist
        CODE_SIGN_STYLE: Automatic
        DEVELOPMENT_ASSET_PATHS: ""
    info:
      path: TimeTrackerVoice/Resources/Info.plist
      properties:
        CFBundleName: TimeTracker Voice
        CFBundleDisplayName: TimeTracker Voice
        CFBundleIdentifier: $(PRODUCT_BUNDLE_IDENTIFIER)
        CFBundleVersion: "1"
        CFBundleShortVersionString: "1.0"
        CFBundlePackageType: APPL
        CFBundleExecutable: $(EXECUTABLE_NAME)
        UILaunchScreen: {}
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
        UIApplicationSceneManifest:
          UIApplicationSupportsMultipleScenes: false
        NSMicrophoneUsageDescription: "TimeTracker Voice needs access to your microphone to enable voice commands for managing your tasks and schedule."
        UIBackgroundModes:
          - audio

