name: TimeTrackerVoice
options:
  bundleIdPrefix: com.timetracker
  deploymentTarget:
    iOS: "17.0"
  xcodeVersion: "15.0"
  generateEmptyDirectories: true

settings:
  base:
    DEVELOPMENT_TEAM: ""
    SWIFT_VERSION: "5.9"
    ENABLE_USER_SCRIPT_SANDBOXING: NO
    # Google Sign-In - Set these in Xcode or via xcconfig
    # Get from Google Cloud Console -> Credentials -> OAuth 2.0 Client IDs -> iOS
    GOOGLE_CLIENT_ID: ""
    GOOGLE_REVERSED_CLIENT_ID: ""

packages:
  GoogleSignIn:
    url: https://github.com/google/GoogleSignIn-iOS
    from: "8.0.0"

targets:
  TimeTrackerVoice:
    type: application
    platform: iOS
    sources:
      - TimeTrackerVoice
    dependencies:
      - package: GoogleSignIn
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.timetracker.voice
        PRODUCT_NAME: Time
        INFOPLIST_FILE: TimeTrackerVoice/Resources/Info.plist
        CODE_SIGN_STYLE: Automatic
        DEVELOPMENT_ASSET_PATHS: ""
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
    scheme:
      testTargets: []
      gatherCoverageData: false

